services:
  - type: web
    name: paroisse-mipa-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_bhrEyX9TYH7G@ep-rapid-sea-ak1v808q-pooler.c-3.us-west-2.aws.neon.tech/ParoisseMipa?sslmode=require&channel_binding=require
      - key: JWT_SECRET
        value: mipa_jwt_secret_paroisse_dakar_2025_xK9pLmQ3
      - key: FRONTEND_URL
        value: https://paroisse-mipa.netlify.app
      - key: NODE_ENV
        value: production
